### PR TITLE
Pass global set proxy settings to mongodb-download

### PR DESCRIPTION
**Pull request by thisispax**
This pull request passes the global set proxy settings to mongodb-download. So as mentioned in this issue (https://github.com/winfinit/mongodb-prebuilt/issues/20) a download through a corporate proxy will be possible.

### CODE REVIEW

**Comment by winfinit** [comment]
mongodb-download allows you to pass opts, to that you can pass agent and your own proxy object

**Comment by thisispax** [comment]
mongoose uses mongodb-prebuilt to get mongodb. but that doesn't work for me because of our proxy... so what would you suggest to do?

**Comment by BenCoffman** [comment]
@pax1878 :+1: 

Please merge @winfinit

**Comment by YellowDarter** [comment]
Having exactly the same problem as @pax1878 - The npm install for mongodb-prebuilt automatically calls mongodb-download, without the ability to pass in the opts anywhere.  @pax1878 's code solves this by using the system-wide proxy environment variable.

Please accept the pull as it will only impact those with the proxy variable set and works well in our testing.

**Comment by winfinit** [comment]
@BenCoffman and @pax1878, I've released new version of Mockgoose 6.0.0 there are small modifications to your unit tests that you would have to do, but it will save you a lot of headache in the future, if you will convert to 6.0 release, that also incorporates requested feature here.

https://www.npmjs.com/package/mongodb-prebuilt#download-proxy

**Comment by thisispax** [comment]
Thanks a lot for your help!

**Comment by BenCoffman** [comment]
#winning :+1:

**Pull request closed without merging**
